apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: department-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: department-app
      labels:
        app: department-app
    spec:
      containers:
        - name: department-app
          image: sai194/department-app
          ports:
           - name: app-port
             containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: department-svc
spec:
  ports:
    - port: 8080
      nodePort: 31008
      targetPort: app-port
      protocol: TCP
  selector:
    app: department-app
  type: NodePort